# Generated by Django 5.0.7 on 2026-03-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
